[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$addonRoot = Split-Path -Parent $PSScriptRoot
$projectRoot = (Resolve-Path (Join-Path $addonRoot '..\..')).Path
$sourceRoot = Join-Path $projectRoot 'tools\ixray-inventory-grouping-full-src\gamedata\configs\gameplay'
$stcopRoot = Join-Path $projectRoot 'ixr_addons\ixray-stcop-wp-3.7-cop-r1.0\configs\gameplay'

$sourceNames = @(
    'character_desc_general.xml',
    'character_desc_zaton.xml',
    'character_desc_pripyat.xml',
    'character_desc_jupiter.xml',
    'character_desc_underpass.xml'
)

$records = [ordered]@{}

function Get-XmlTagValue {
    param([string]$Block, [string]$Tag)
    $match = [regex]::Match($Block, "<$Tag>(.*?)</$Tag>", [Text.RegularExpressions.RegexOptions]::Singleline)
    if (-not $match.Success) { return '' }
    return ($match.Groups[1].Value -replace '\s+', ' ').Trim()
}

function Add-CharacterFile {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) {
        throw "Required profile source is missing: $Path"
    }
    $xml = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
    $matches = [regex]::Matches(
        $xml,
        '<specific_character\s+id="([^"]+)"[^>]*>(.*?)</specific_character>',
        [Text.RegularExpressions.RegexOptions]::Singleline
    )
    foreach ($match in $matches) {
        $id = $match.Groups[1].Value.Trim()
        if ($id -in @('actor', 'mp_actor') -or $id -eq '') { continue }
        $block = $match.Groups[2].Value
        $name = Get-XmlTagValue -Block $block -Tag 'name'
        $community = Get-XmlTagValue -Block $block -Tag 'community'
        $visual = Get-XmlTagValue -Block $block -Tag 'visual'
        $class = Get-XmlTagValue -Block $block -Tag 'class'
        if ($class -eq '') { $class = 'Stalker_general' }
        $weapon = [regex]::IsMatch($block, '\bwpn_[a-zA-Z0-9_]+\b')
        $risk = 'story'
        if ($id -match '^sim_default_') { $risk = 'generic' }
        if ($id -match '(corpse|dead|dying|wounded)' -or $block -match '<health>\s*0') { $risk = 'corpse' }
        $records[$id] = [pscustomobject]@{
            Id = $id
            Name = $name
            Community = $community
            Visual = $visual
            Class = $class
            Weapon = if ($weapon) { 'armed' } else { 'unarmed' }
            Risk = $risk
        }
    }
}

foreach ($name in $sourceNames) {
    Add-CharacterFile -Path (Join-Path $sourceRoot $name)
}

foreach ($name in @('character_desc_general.xml', 'character_desc_zaton.xml', 'character_desc_jupiter.xml')) {
    $override = Join-Path $stcopRoot $name
    if (Test-Path -LiteralPath $override) { Add-CharacterFile -Path $override }
}

$profiles = @($records.Values | Sort-Object Risk, Community, Id)
$profileXml = [Collections.Generic.List[string]]::new()
$profileXml.Add('<?xml version="1.0" encoding="utf-8"?>')
$profileXml.Add('<xml>')

$ltx = [Collections.Generic.List[string]]::new()
$ltx.Add('; GENERATED by tools\generate_profiles.ps1. Do not edit manually.')
$ltx.Add('![profiles]')
$ltx.Add('>files = npc_profile_pf_npc_editor')
$ltx.Add('')
$ltx.Add('[pf_npc_editor_catalog]')
$ltx.Add("count = $($profiles.Count)")

for ($index = 0; $index -lt $profiles.Count; $index++) {
    $item = $profiles[$index]
    $number = $index + 1
    $suffix = '{0:D4}' -f $number
    $profileId = "pf_ne_profile_$suffix"
    $section = "pf_ne_npc_$suffix"
    $safeName = ($item.Name -replace '[|;\r\n]', ' ').Trim()
    $safeCommunity = ($item.Community -replace '[|;\r\n]', ' ').Trim()
    $safeVisual = ($item.Visual -replace '[|;\r\n]', ' ').Trim()

    $profileXml.Add("`t<character id=`"$profileId`">")
    $profileXml.Add("`t`t<class>$($item.Class)</class>")
    $profileXml.Add("`t`t<specific_character>$($item.Id)</specific_character>")
    $profileXml.Add("`t</character>")

    $ltx.Add("entry_$suffix = $section|$profileId|$($item.Id)|$safeName|$safeCommunity|$safeVisual|$($item.Risk)|$($item.Weapon)")
}

$ltx.Add('')
$ltx.Add('[pf_npc_editor_immunities]')
foreach ($line in @(
    'burn_immunity = 0.0',
    'strike_immunity = 0.0',
    'shock_immunity = 0.0',
    'wound_immunity = 0.0',
    'radiation_immunity = 0.0',
    'telepatic_immunity = 0.0',
    'chemical_burn_immunity = 0.0',
    'explosion_immunity = 0.0',
    'fire_wound_immunity = 0.0'
)) { $ltx.Add($line) }

for ($index = 0; $index -lt $profiles.Count; $index++) {
    $number = $index + 1
    $suffix = '{0:D4}' -f $number
    $profileId = "pf_ne_profile_$suffix"
    $section = "pf_ne_npc_$suffix"
    $ltx.Add('')
    $ltx.Add("[$section]:stalker")
    $ltx.Add('$spawn = ""')
    $ltx.Add("character_profile = $profileId")
    $ltx.Add('script_binding = bind_stalker.init')
    $ltx.Add('custom_data = scripts\pf_npc_editor\editor_owned.ltx')
    $ltx.Add('immunities_sect = pf_npc_editor_immunities')
}

$profileXml.Add('</xml>')

$profilePath = Join-Path $addonRoot 'configs\gameplay\npc_profile_pf_npc_editor.xml'
$ltxPath = Join-Path $addonRoot 'configs\mod_system_pf_npc_editor_profiles.ltx'
[IO.File]::WriteAllLines($profilePath, $profileXml, [Text.UTF8Encoding]::new($false))
[IO.File]::WriteAllLines($ltxPath, $ltx, [Text.UTF8Encoding]::new($false))
Write-Host "Generated $($profiles.Count) exact NPC profiles."
Write-Host $profilePath
Write-Host $ltxPath
